name: camsecurity
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # Bajamos de 3.10.7 a 3.1.0 para que coincida con el servidor de GitHub
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.3+1
  qr_flutter: ^4.1.0
  device_info_plus: ^12.3.0
  mobile_scanner: ^7.1.4
  path_provider: ^2.1.5
  http: ^1.6.0
  google_fonts: ^8.0.1
  permission_handler: ^12.0.1
  flutter_webrtc: ^0.12.3
  flutter_background_service: ^5.0.12
  crypto: ^3.0.6
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  video_player: ^2.8.1
  chewie: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo/logo.jpg"
  min_sdk_android: 21
