name: camsecurity
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.3+1
  qr_flutter: ^4.1.0
  # Ajustamos device_info_plus y crypto a versiones compatibles con Dart 3.1
  device_info_plus: ^9.0.2
  crypto: ^3.0.3
  mobile_scanner: ^7.1.4
  path_provider: ^2.1.5
  http: ^1.1.0
  google_fonts: ^5.1.0
  permission_handler: ^11.0.1
  flutter_webrtc: ^0.10.4
  flutter_background_service: ^5.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  video_player: ^2.7.1
  chewie: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo/logo.jpg"
  min_sdk_android: 21
